In [4]:
import pandas as pd
import numpy as np

In [40]:
df = pd.read_csv("OMG.csv", dtype = str)

In [41]:
df.head()

,Unnamed: 0,product_name,product_id,rank,category,item_price,also_viewed,bought_together,also_bought
0,0,Purple Sequin Tiny Dancer Tutu Ballet Dance Fa...,0000037214,1233557,Clothing,440.37,"'B00JO8II76', 'B00DGN4R1Q', 'B00E1YRI4C'",NaN,NaN
1,1,Ballet Dress-Up Fairy Tutu,0000031887,8547,Sports &amp; Outdoors,427.77,"'B00E1YRI4C', 'B00D23MC6W', 'B00AFDOPDA', 'B00...",'B00D23MC6W',"'0000031852', '0000031895', '0000031909', 'B00..."
2,2,SHINING IMAGE HUGE PINK LEATHER JEWELRY BOX / ...,0123456479,16987,Kitchen & Dining,4093.7400000000002,"'B0006JCGUM', 'B000BMTCK6', 'B00194Q262', 'B00...","'B000BMTCK6', 'B0006JCGUM'","'B000BMTCK6', 'B0006JCGUM', 'B00194Q262', 'B00..."
3,3,RiZ Women's Beautify Crafted &frac12; Rimmed F...,0456844570,1180499,Clothing,NaN,"'B008MTRT1O', 'B00BUG47S4', 'B00GTVY0DC', 'B00...",NaN,NaN
4,4,Lantin White Visor Wrap Around Ski Style Aviat...,0456808574,1038084,Clothing,NaN,"'B00A6JD8EA', 'B00BFL4FTA', 'B00JPI9AAO', 'B00...",NaN,NaN

In [42]:
df = df.drop(["Unnamed: 0"],axis=1)

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1503384 entries, 0 to 1503383
Data columns (total 8 columns):
product_name       1502696 non-null object
product_id         1503384 non-null object
rank               1421649 non-null object
category           1421649 non-null object
item_price         574882 non-null object
also_viewed        1001533 non-null object
bought_together    646136 non-null object
also_bought        444130 non-null object
dtypes: object(8)
memory usage: 91.8+ MB

In [44]:
# cols = [c for c in df.row if c != 'Clothing']

In [90]:
row = df[df.rows.drop(list(df.filter(regex='Clothing')))]

AttributeError: 'DataFrame' object has no attribute 'rows'

In [91]:
row = df[df['category'].isin(['Clothing'])]
import random
rand = df["item_price"].fillna(np.random.randn()**2)

In [88]:
rand.head()

0                440.37
1                427.77
2    4093.7400000000002
3              0.697622
4              0.697622
Name: item_price, dtype: object

In [ ]:
# rand["dd"] = np.random.randn(len(X[np.isnan(X)]))

In [70]:
# rand["item_price"].max()
rand = rand.to_frame().astype(float)

In [64]:
rand.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1503384 entries, 0 to 1503383
Data columns (total 1 columns):
item_price    1503384 non-null float64
dtypes: float64(1)
memory usage: 11.5 MB

In [92]:
# row["price"] = rand["item_price"]

In [93]:
row.head()

,product_name,product_id,rank,category,item_price,also_viewed,bought_together,also_bought
0,Purple Sequin Tiny Dancer Tutu Ballet Dance Fa...,0000037214,1233557,Clothing,440.37,"'B00JO8II76', 'B00DGN4R1Q', 'B00E1YRI4C'",NaN,NaN
3,RiZ Women's Beautify Crafted &frac12; Rimmed F...,0456844570,1180499,Clothing,NaN,"'B008MTRT1O', 'B00BUG47S4', 'B00GTVY0DC', 'B00...",NaN,NaN
4,Lantin White Visor Wrap Around Ski Style Aviat...,0456808574,1038084,Clothing,NaN,"'B00A6JD8EA', 'B00BFL4FTA', 'B00JPI9AAO', 'B00...",NaN,NaN
7,Max-MPH Black - Large Wayfarer Sunglasses Avai...,0456840532,2728771,Clothing,NaN,"'B001K9DPPC', 'B00BV9MU2K', 'B0042FHTDK', 'B00...",NaN,NaN
8,FX1 Small Adult Aviator Sunglasses with Silver...,0456787283,456854,Clothing,NaN,"'B00AIPLH22', 'B005P1H8KO', 'B00CMCVKC6', 'B00...",NaN,NaN

In [96]:
row = row.drop(["category"],axis=1).sort_values("rank")

In [102]:
df.loc[df['rank'] == '2']

,product_name,product_id,rank,category,item_price,also_viewed,bought_together,also_bought
25362,Sanuk Women's Yoga Mat Flip Flop,B000DZUGOM,2,Shoes,NaN,'B00AE3K1I4',NaN,NaN
25371,Sanuk Women's Yoga Mat Flip Flop,B000DZZFLG,2,Shoes,NaN,"'B00009XO58', 'B002JLLSGS', 'B003XNTRSC', 'B00...",NaN,NaN
25372,Sanuk Women's Yoga Mat Flip Flop,B000DZZFL6,2,Shoes,NaN,"'B005BQYJP0', 'B009IGDM52', 'B004Z4CFUK', 'B00...",NaN,NaN
25374,Sanuk Women's Yoga Mat Flip Flop,B000DZZFUW,2,Shoes,NaN,"'B001D06HSA', 'B007ULYN3W'",NaN,NaN
25376,Sanuk Women's Yoga Mat Flip Flop,B000DZZFLQ,2,Shoes,NaN,"'B003HC9GVM', 'B00FS6UORK', 'B004UBUT0Q', 'B00...",'B003HC9GVM',"'B003HC9GVM', 'B00FS6UORK'"
762180,Alex and Ani &quot;Bangle Bar&quot; Birthstone...,B007UMDB0C,2,Jewelry,1673.28,"'B00E8FQPPW', 'B00E8FQYP8', 'B00E8FQJCQ', 'B00...","'B00E8FQPPW', 'B00E8FQYP8', 'B00E8FQJCQ', 'B00...","'B00E8FQYP8', 'B00E8FQJCQ', 'B00E8FQPPW', 'B00..."
762188,Alex and Ani &quot;Bangle Bar&quot; Birthstone...,B007UMDB7U,2,Jewelry,1719.27,"'B009MAMLQ0', 'B00EFETG34', 'B00H2BWKW6', 'B00...",NaN,NaN
762192,Alex and Ani &quot;Bangle Bar&quot; Birthstone...,B007UMDB02,2,Jewelry,1673.28,"'B00E8FQOUS', 'B00B4A95RO', 'B0061J8Y0C', 'B00...","'B00B4A95RO', 'B00E8FQOUS', 'B0061J8Y0C', 'B00...","'B00E8FQOUS', 'B00E8FQOQC', 'B00B4A95RO', 'B00..."
762194,Alex and Ani &quot;Bangle Bar&quot; Birthstone...,B007UMDBNY,2,Jewelry,1673.28,"'B00E8FQOUS', 'B00B4A95RO', 'B0061J8Y0C', 'B00...","'B00B4A95RO', 'B00E8FQOUS', 'B0061J8Y0C', 'B00...","'B00E8FQOUS', 'B00E8FQOQC', 'B00B4A95RO', 'B00..."
762195,Alex and Ani &quot;Bangle Bar&quot; Birthstone...,B007UMDB7A,2,Jewelry,1719.27,"'B0061J8Y0C', 'B00E8FQU8O', 'B00E8FQFMA', 'B00...","'B0061J8Y0C', 'B00E8FQU8O', 'B00BLQ8FBI', 'B00...","'B0061J8Y0C', 'B00E8FQU8O', 'B00BLQ8FBI', 'B00..."
762196,Alex and Ani &quot;Bangle Bar&quot; Birthstone...,B007UMDBP2,2,Jewelry,1764.0,"'B00E8FQPPW', 'B00E8FQYP8', 'B00E8FQJCQ', 'B00...","'B00E8FQPPW', 'B00E8FQYP8', 'B00E8FQJCQ', 'B00...","'B00E8FQYP8', 'B00E8FQJCQ', 'B00E8FQPPW', 'B00..."
762199,Alex and Ani &quot;Bangle Bar&quot; Birthstone...,B007UMDBMU,2,Jewelry,1764.0,"'B00E8FQYP8', 'B00E8FQU3O', 'B00BLQ8C9I', 'B00...","'B00E8FQU3O', 'B00E8FQYP8', 'B0061J8Y0C', 'B00...","'B00E8FQU3O', 'B00E8FQYP8', 'B00BZ1IERO', 'B00..."
762203,Alex and Ani &quot;Bangle Bar&quot; Birthstone...,B007UMDBWU,2,Jewelry,1673.28,"'B0064TL8FM', 'B0064TLABE', 'B002EBH2O0', 'B00...","'B0064TLABE', 'B00JIY3MJK', 'B0064TL8FM', 'B00...",NaN
762209,Alex and Ani &quot;Bangle Bar&quot; Birthstone...,B007UMDB6Q,2,Jewelry,1673.28,"'B00E8FQYP8', 'B00E8FQKUM', 'B00E8FQJCQ', 'B00...","'B00E8FQYP8', 'B00E8FQKUM', 'B00BLQ88CO', 'B00...","'B00E8FQYP8', 'B00E8FQKUM', 'B00E8FQJCQ', 'B00..."
762217,Alex and Ani &quot;Bangle Bar&quot; Birthstone...,B007UMDBW0,2,Jewelry,1673.28,"'B00DJMGYK6', 'B00D0QXXSM', 'B00FKMT5DG', 'B00...","'B00DJMGYK6', 'B00AJF4H5A', 'B00D1JLHD6', 'B00...",NaN
762219,Alex and Ani &quot;Bangle Bar&quot; Birthstone...,B007UMDBDO,2,Jewelry,1764.0,"'B009W1HQVO', 'B004SCYMBE', 'B00DR2PU76', 'B00...","'B009W1HQVO', 'B004SCYMBE', 'B00DR2PU76', 'B00...","'B00DR2PU76', 'B004SCYMBE', 'B00ES5IT88', 'B00..."
762231,Alex and Ani &quot;Bangle Bar&quot; Birthstone...,B007UMDBWA,2,Jewelry,1673.28,"'B00E8FQOAI', 'B00B4A95RO', 'B00E8FQUK2', 'B00...","'B00B4A95RO', 'B00E8FQOAI', 'B00E8FQUK2', 'B00...","'B00E8FQOAI', 'B00E8FQUK2', 'B00E8FQOQC', 'B00..."
762233,Alex and Ani &quot;Bangle Bar&quot; Birthstone...,B007UMDBX4,2,Jewelry,1620.36,"'B008G5J2MI', 'B00A4LKUUK', 'B00EENWD9A', 'B00...",NaN,NaN
762235,Alex and Ani &quot;Bangle Bar&quot; Birthstone...,B007UMDBD4,2,Jewelry,1673.28,"'B0064TL8FM', 'B0064TLABE', 'B002EBH2O0', 'B00...","'B0064TLABE', 'B00JIY3MJK', 'B0064TL8FM', 'B00...",NaN
762236,Alex and Ani &quot;Bangle Bar&quot; Birthstone...,B007UMDB0M,2,Jewelry,1673.28,"'B00AG0V81O', 'B00E1PAOR4', 'B00JG3HJYW', 'B00...","'B00D1KJ1Q0', 'B00AG0V81O'",NaN
762239,Alex and Ani &quot;Bangle Bar&quot; Birthstone...,B007UMDC5G,2,Jewelry,1673.28,"'B00D1K370Q', 'B003TU20BK', 'B001S7L5D0', 'B00...",NaN,NaN
762248,Alex and Ani &quot;Bangle Bar&quot; Birthstone...,B007UMDBN4,2,Jewelry,1673.28,"'B002KKD05U', 'B004LY50TM', 'B00E8AP4BS', 'B00...","'B002KKD05U', 'B00EE7J0RO', 'B008HXU6P6', 'B00...","'B00EE7J0RO', 'B00E8AP4BS', 'B002KKD05U', 'B00..."
762255,Alex and Ani &quot;Bangle Bar&quot; Birthstone...,B007UMDB70,2,Jewelry,1719.27,"'B002KKD05U', 'B004LY50TM', 'B00E8AP4BS', 'B00...","'B002KKD05U', 'B00EE7J0RO', 'B008HXU6P6', 'B00...","'B00EE7J0RO', 'B00E8AP4BS', 'B002KKD05U', 'B00..."
762260,Alex and Ani &quot;Bangle Bar&quot; Birthstone...,B007UMDBOS,2,Jewelry,1673.28,"'B00B4A95RO', 'B00E8FQOUS', 'B00E8FQOAI', 'B00...","'B00B4A95RO', 'B00E8FQOUS', 'B0061J8Y0C', 'B00...","'B00B4A95RO', 'B00E8FQOUS', 'B00E8FQOAI', 'B00..."
762261,Alex and Ani &quot;Bangle Bar&quot; Birthstone...,B007UMDB7K,2,Jewelry,1673.28,"'B002KKD05U', 'B004LY50TM', 'B00E8AP4BS', 'B00...","'B002KKD05U', 'B00EE7J0RO', 'B008HXU6P6', 'B00...","'B00EE7J0RO', 'B00E8AP4BS', 'B002KKD05U', 'B00..."
762271,Alex and Ani &quot;Bangle Bar&quot; Birthstone...,B007UMDBF2,2,Jewelry,1673.28,"'B00E8FQTZS', 'B00B4A8QLK', 'B00E8FQPPW', 'B00...","'B00B4A8QLK', 'B00E8FQTZS', 'B0061J8Y0C', 'B00...","'B00E8FQJCQ', 'B00B4A8QLK', 'B00E8FQTZS', 'B00..."
762274,Alex and Ani &quot;Bangle Bar&quot; Birthstone...,B007UMDBES,2,Jewelry,1719.27,"'B002IFSURK', 'B00E8FQFMA', 'B00B4A95RO', 'B00...","'B00E8FQU8O', 'B00B4A95RO', 'B002IFSURK', 'B00...","'B00E8FQU8O', 'B00B4A95RO', 'B00E8FQFMA', 'B00..."
762282,Alex and Ani &quot;Bangle Bar&quot; Birthstone...,B007UMDBFC,2,Jewelry,1673.28,"'B00D7IDIP6', 'B00E8AP60W', 'B003UTU4AY', 'B00...","'B00D7IDIP6', 'B006PFQXUU', 'B00E8FRTZW', 'B00...","'B00E8FRTZW', 'B00D7IDIP6', 'B00E8AP60W', 'B00..."
762291,Alex and Ani &quot;Bangle Bar&quot; Birthstone...,B007UMDBVG,2,Jewelry,1673.28,"'B00D7IDIP6', 'B003UTU4AY', 'B00E8AP70G', 'B00...","'B00D7IDIP6', 'B005O65HJ4', 'B006PFQXUU', 'B00...","'B00D7IDIP6', 'B00E8AP6V6', 'B00E8AP70G', 'B00..."
1473759,Jacted Up Tees I 8 Sum Pi and it was Delicious...,B00IQWMYAI,2,Clothing,NaN,NaN,NaN,NaN

In [97]:
row.head()

,product_name,product_id,rank,item_price,also_viewed,bought_together,also_bought
1490553,Generic Disney Frozen Dress Princess Elsa Girl...,B00JL81OWA,1,NaN,NaN,NaN,NaN
1490574,Generic Disney Frozen Dress Princess Elsa Girl...,B00JL81OUC,1,NaN,NaN,NaN,NaN
1490559,Generic Disney Frozen Dress Princess Elsa Girl...,B00JL81P38,1,NaN,NaN,NaN,NaN
1490546,Generic Disney Frozen Dress Princess Elsa Girl...,B00JL81P06,1,NaN,NaN,NaN,NaN
1000466,Hanes Men's Classics Five-Pack Boxer Brief - C...,B00ACIGVIK,10,NaN,'B00KQVADGY',NaN,NaN

In [94]:
row.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 657651 entries, 0 to 1503383
Data columns (total 8 columns):
product_name       657645 non-null object
product_id         657651 non-null object
rank               657651 non-null object
category           657651 non-null object
item_price         245333 non-null object
also_viewed        378218 non-null object
bought_together    242514 non-null object
also_bought        167302 non-null object
dtypes: object(8)
memory usage: 45.2+ MB

In [95]:
row.to_csv("just_clothing.csv")

In [38]:
row['item_price'] = row['item_price'].fillna(0)

In [39]:
row.head()

,product_name,product_id,rank,category,item_price,also_viewed,bought_together,also_bought
0,Purple Sequin Tiny Dancer Tutu Ballet Dance Fa...,0000037214,1233557,Clothing,440.37,"'B00JO8II76', 'B00DGN4R1Q', 'B00E1YRI4C'",NaN,NaN
3,RiZ Women's Beautify Crafted &frac12; Rimmed F...,0456844570,1180499,Clothing,0,"'B008MTRT1O', 'B00BUG47S4', 'B00GTVY0DC', 'B00...",NaN,NaN
4,Lantin White Visor Wrap Around Ski Style Aviat...,0456808574,1038084,Clothing,0,"'B00A6JD8EA', 'B00BFL4FTA', 'B00JPI9AAO', 'B00...",NaN,NaN
7,Max-MPH Black - Large Wayfarer Sunglasses Avai...,0456840532,2728771,Clothing,0,"'B001K9DPPC', 'B00BV9MU2K', 'B0042FHTDK', 'B00...",NaN,NaN
8,FX1 Small Adult Aviator Sunglasses with Silver...,0456787283,456854,Clothing,0,"'B00AIPLH22', 'B005P1H8KO', 'B00CMCVKC6', 'B00...",NaN,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1503384 entries, 0 to 1503383
Data columns (total 8 columns):
product_name       1502696 non-null object
product_id         1503384 non-null object
rank               1421649 non-null object
category           1421649 non-null object
item_price         574882 non-null object
also_viewed        1001533 non-null object
bought_together    646136 non-null object
also_bought        444130 non-null object
dtypes: object(8)
memory usage: 91.8+ MB

In [33]:
row

,product_name,product_id,rank,category,item_price,also_viewed,bought_together,also_bought
0,Purple Sequin Tiny Dancer Tutu Ballet Dance Fa...,0000037214,1233557,Clothing,440.37,"'B00JO8II76', 'B00DGN4R1Q', 'B00E1YRI4C'",NaN,NaN
3,RiZ Women's Beautify Crafted &frac12; Rimmed F...,0456844570,1180499,Clothing,NaN,"'B008MTRT1O', 'B00BUG47S4', 'B00GTVY0DC', 'B00...",NaN,NaN
4,Lantin White Visor Wrap Around Ski Style Aviat...,0456808574,1038084,Clothing,NaN,"'B00A6JD8EA', 'B00BFL4FTA', 'B00JPI9AAO', 'B00...",NaN,NaN
7,Max-MPH Black - Large Wayfarer Sunglasses Avai...,0456840532,2728771,Clothing,NaN,"'B001K9DPPC', 'B00BV9MU2K', 'B0042FHTDK', 'B00...",NaN,NaN
8,FX1 Small Adult Aviator Sunglasses with Silver...,0456787283,456854,Clothing,NaN,"'B00AIPLH22', 'B005P1H8KO', 'B00CMCVKC6', 'B00...",NaN,NaN
9,Riz Small Unisex (Mens/ Womens) Black Classic ...,0456838384,437391,Clothing,NaN,"'B001K9DPPC', 'B0042FHTDK', 'B00DGJJI0U', 'B00...",NaN,NaN
30,Carter's Basic White SLEEVELESS Bodysuits,1412718031,8049,Clothing,1386.0,"'B00EPHEZJG', 'B001AL7ONO', 'B00GGAE5FO', 'B00...","'B00CZ8YX8K', 'B00BWZ94P4'",NaN
32,2013 Desk Pad Calendar,1465014578,505645,Clothing,NaN,"'B00CZ8YX8K', 'B00CYG0M2E', 'B00BWZ94P4', 'B00...",NaN,NaN
41,Bambino Balls Short Sleeve Tennis Outfit,1608322181,209439,Clothing,NaN,"'B00652TRR4', 'B00D8GLOTY', 'B00652U2ZK', 'B00...","'B00652TRR4', 'B00693I356', 'B00652UIE0', 'B00...","'B00693I356', 'B00652TRR4', 'B00652UIE0', 'B00..."
42,Bambino Balls Short Sleeve Soccer Outfit,1608322130,30744,Clothing,NaN,"'B00D8GLOTY', 'B002BE6VIS', 'B00652U2ZK', 'B00...","'B002BE6VIS', 'B00693I356'","'B002BE6VIS', 'B00693I356', 'B007MB6J14', 'B00..."
43,Bambino Balls Short Sleeve Football Outfit Bro...,1608322262,28553,Clothing,NaN,"'B00652TRR4', 'B00652UFU2', 'B00693I356', 'B00...","'B00693I356', 'B00652TGLQ', 'B00652TRR4'","'B00693I356', 'B00652TRR4', 'B00652TGLQ', 'B00..."
75,La Leela Men's Hawaiian Print Shirt,245600258X,3575,Clothing,NaN,"'B002WN2L6O', 'B00EO17NKQ', 'B0062N0EU0', 'B00...","'B0080IFJ78', 'B00BH8NVKU', 'B002WN2L6O', 'B00...","'B0080IFJ78', 'B00EO17NKQ', 'B00BH8NVKU', 'B00..."
77,Kukishinden Ry&ucirc; (Bujinkan Bud&ocirc; Den...,3924862206,576793,Clothing,NaN,'B00DI6WQVE',NaN,NaN
78,Fuente Deluxe Aniline Leather Pants black for Men,3999837810,138136,Clothing,11277.0,"'B00BSW70OS', 'B003VDZ3NM', 'B0083MZDYA', 'B00...",NaN,NaN
80,Bockle&reg; New York Leatherjeans Men Pants Le...,3999847743,484677,Clothing,NaN,'B0069BUI06',NaN,NaN
81,Fuente Lion Brown Leather Pants trousers Germany,3999838167,1302944,Clothing,9135.0,'B00BGBV3IA',NaN,NaN
83,Leather Trousers Bockle Men's Saddle Lederjean...,481713996X,479034,Clothing,14427.0,"'B00HVH69SC', 'B00HZ1ELIY', 'B008O7UPKG'","'B00HZ1ELIY', 'B004HUBED6', 'B008O7UPKG', 'B00...",NaN
91,Top Gear Official Merchandise - Seriously Uncool,5555015097,747512,Clothing,1445.85,"'B00DZQDA26', 'B00HTH1RDG', 'B00HTH1MWW', 'B00...",NaN,NaN
92,Top Gear Official Merchandise - Captain Slow T...,5555014368,501853,Clothing,1445.85,"'B008ZPZ9KS', 'B006CIHP7U', 'B006CIHP4S', 'B00...","'B008ZPZ9KS', 'B006CIHP7U', 'B006CIHP4S', 'B00...",NaN
93,Top Gear Official Merchandise - Stig Black,5555012322,69476,Clothing,1445.85,"'B00BNX6KHA', 'B00HTH1RDG', 'B00K5200X0', 'B00...",NaN,NaN
94,Top Gear Official Merchandise - Stig Navy,555501239X,192392,Clothing,1445.85,"'B00CJVOWPC', 'B00EIGHAWS', 'B00GGG1JE8', 'B00...",NaN,NaN
95,Top Gear Official Merchandise - Stig Black,5555012349,69476,Clothing,1445.85,"'B001AKC25A', 'B0054V1270', 'B00BMV6MW6', 'B00...","'B0054V1270', 'B007IYLLBI', 'B001AKC25A', 'B00...","'B0054V1270', 'B00E7TQWBG', 'B0091USIH2', 'B00..."
96,Official Top Gear 'My Dad is The Stig' T-Shirt,5555014090,124479,Clothing,1244.25,"'B009FSVI5O', 'B001AKC25A', 'B007LNW10G', 'B00...",NaN,NaN
97,Top Gear Official Merchandise - NOT the Stig,5555015038,265429,Clothing,1445.85,'B008ESLL1M',NaN,NaN
98,Top Gear Official Merchandise - Stig Black,5555012330,69476,Clothing,1445.85,"'B00FPNZ6T2', 'B00K5200X0', 'B000YD2C3G', 'B00...",NaN,NaN
99,Top Gear Official Merchandise - Sub Zero,5555015119,559807,Clothing,1445.85,"'B00CJVOWPC', 'B008STCQ5M', 'B00K5200X0', 'B00...",NaN,NaN
106,Sevendayz Men's The Weeknd Xo Long Sleeve Base...,6041006041,1641903,Clothing,1830.78,"'B00HTH1RDG', 'B00KFH83ES', 'B00DZQDA26', 'B00...",NaN,NaN
124,High Quality! Very Vivid! Angry Birds Adult Si...,7801784235,1960135,Clothing,NaN,"'B00CRS2TL6', 'B00BK6HPRE', 'B00AG8GU9Q', 'B00...",NaN,NaN
128,Emaan's Men Faux Leather Bane Vest,7890004311,598476,Clothing,9449.37,"'B0042Z6YF4', 'B0042Z9IUW', 'B0084Z4ZPE', 'B00...","'B0042Z6YF4', 'B0042Z9IUW', 'B0084Z4ZPE', 'B00...","'B0042Z6YF4', 'B0042Z9IUW', 'B0084Z4ZPE', 'B00..."
132,A1 MAX - Anime Costume Party Cosplay Short Cur...,8181475135,80991,Clothing,629.37,"'B008DD51O6', 'B004301ZL6', 'B008DD510A', 'B00...","'B004301ZL6', 'B008DD51O6', 'B008DD510A', 'B00...","'B004301ZL6', 'B008DD510A', 'B008DD51O6', 'B00..."
...,...,...,...,...,...,...,...,...
1503322,Eyekepper Women's Sleeveless Back Zip Ruffled ...,B00LIR0AO0,382724,Clothing,NaN,NaN,NaN,NaN
1503324,Anna Deluxe Dress Anna Costume Child 57005,B00LJ8LM0O,349733,Clothing,2449.44,NaN,NaN,NaN
1503327,Dress Like A Pirate Historically Accurate Heav...,B00LJGRO9Y,93409,Clothing,NaN,NaN,NaN,NaN
1503328,Dress Like A Pirate Historically Accurate Heav...,B00LJGRNPO,93409,Clothing,NaN,NaN,NaN,NaN
1503329,Snow Camo Gown Lingerie + Realtree Max-4 Camo ...,B00LJXU59S,756681,Clothing,3118.5,NaN,NaN,NaN
1503331,Mossy Oak Camo Gown Lingerie + Realtree Max-4 ...,B00LJYA31C,773358,Clothing,3149.3700000000003,NaN,NaN,NaN
1503336,Mossy Oak Camo Gown Lingerie + Realtree Max-4 ...,B00LJYA2ZY,773358,Clothing,3149.3700000000003,NaN,NaN,NaN
1503339,My Little Pony Animal Print 16 Inch Backpack,B00LKS8LY8,18909,Clothing,1133.37,NaN,NaN,NaN
1503341,New Fashion Sexy women's One Piece Halter Deep...,B00LL0F6NY,128614,Clothing,1322.37,NaN,NaN,NaN
1503342,Angel-fashions Women's One Shoulder Twinkling ...,B00LL6OYZO,49783,Clothing,3086.3700000000003,NaN,NaN,NaN
1503343,2-Pack Naked North Snow + Pink Camo Juniors Bo...,B00LLHU588,588071,Clothing,2519.3700000000003,NaN,NaN,NaN
1503344,2-Pack Naked North Snow + Pink Camo Juniors Bo...,B00LLHU58S,588071,Clothing,2519.3700000000003,NaN,NaN,NaN
1503345,Pro Packing Cubes - 4 Piece Travel Cubes Set f...,B00LLMEW4Q,7522,Clothing,2206.26,NaN,NaN,NaN
1503346,Digital Hanging/Fishing/Luggage Scale - 2 Pack,B00LLT8PUG,273982,Clothing,252.0,NaN,NaN,NaN
1503347,Push up Leopard Swimsuit Swimwear Bathing Suit...,B00LM6TC0U,460760,Clothing,619.29,NaN,NaN,NaN
1503348,SNS WOMEN EMBROIDERED WRAP PANT RAYON ACID WAS...,B00LMA62UO,50870,Clothing,1259.37,NaN,NaN,NaN
1503350,Metal Mulisha Baby Shirt (6-24M),B00LMEMMN6,405078,Clothing,1067.85,NaN,NaN,NaN
1503351,COQUETA Brazilian Teeny Micro Thong Mini Bikin...,B00LMJOSZG,19683,Clothing,NaN,NaN,NaN,NaN
1503353,New Women's Scrawl Print Romper 2 Pieces Tank ...,B00LMPZL0G,34094,Clothing,1007.37,NaN,NaN,NaN
1503356,ROSEMANDY Women's Sexy Halter Backless Elastic...,B00LN3TT5K,77912,Clothing,314.37,NaN,NaN,NaN
1503357,American Apparel Dark Wash High-Waist Jean Cuf...,B00LN3ZF7G,1201093,Clothing,3654.0,NaN,NaN,NaN
1503361,Dri-Fit Tactical Military Camo Combat Mock Pai...,B00LOGH6JM,16429,Clothing,1763.37,NaN,NaN,NaN
1503362,BeWild Brand&reg; - LeBron James Forgiven Welc...,B00LNSQIC2,4983,Clothing,818.37,NaN,NaN,NaN
1503366,Kenneth Cole Reaction Mens Big &amp; Tall Leat...,B00LPJGHHK,592252,Clothing,1256.85,NaN,NaN,NaN
1503369,Chouyatou Men's Pu Leather Mid-length Washed T...,B00LQH0SM6,252997,Clothing,4724.37,NaN,NaN,NaN
1503371,Baby Girls 3rd Birthday Toddler Tutu Tank Top ...,B00LR6CCXO,139661,Clothing,2329.11,NaN,NaN,NaN
1503374,Musical Holiday Women's Sateen Bridal Wedding ...,B00LT2HE7A,177976,Clothing,4095.0,NaN,NaN,NaN
1503377,Bbmour-kids Girls Boys Frozen Anna and Elsa Pr...,B00LR9X7WQ,56597,Clothing,566.37,NaN,NaN,NaN
1503382,Skirts 'N Scarves Women's Long Cotton Maxi Pai...,B00LWWANMU,521540,Clothing,1259.37,NaN,NaN,NaN
1503383,American Posh Baby Short Sleeve Onesie,B00LZSAV2I,265633,Clothing,3149.3700000000003,NaN,NaN,NaN